openapi: 3.0.0
info:
  title: API de Autenticação e Gestão de Utilizadores
  description: API para autenticação de utilizadores e gestão de dados de utilizadores e tabelas nutricionais.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /registerdev:
    post:
      summary: Registar um novo utilizador com nível de acesso de desenvolvedor.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: Utilizador registado com sucesso.
        '400':
          description: Email inválido ou email já registado.
        '500':
          description: Erro interno do servidor ao registar utilizador.
  /register:
    post:
      summary: Registar um novo utilizador.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: Utilizador registado com sucesso.
        '400':
          description: Email inválido ou email já registado.
        '500':
          description: Erro interno do servidor ao registar utilizador.
  /login:
    post:
      summary: Autenticar um utilizador.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Utilizador autenticado com sucesso. Retorna token de acesso.
        '401':
          description: Credenciais inválidas.
        '500':
          description: Erro interno do servidor ao autenticar utilizador.
  /user/editar/{id}:
    put:
      summary: Editar um utilizador existente.
      parameters:
        - name: id
          in: path
          description: ID do utilizador a ser editado.
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Dados do utilizador atualizados com sucesso.
        '400':
          description: Acesso proibido ou dados inválidos.
        '404':
          description: Utilizador não encontrado.
        '500':
          description: Erro interno do servidor ao editar utilizador.
  /users/eliminar/{id}:
    delete:
      summary: Eliminar um utilizador existente.
      parameters:
        - name: id
          in: path
          description: ID do utilizador a ser eliminado.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Utilizador eliminado com sucesso.
        '403':
          description: Acesso proibido.
        '404':
          description: Utilizador não encontrado.
        '500':
          description: Erro interno do servidor ao eliminar utilizador.
  /users:
    get:
      summary: Obter informações de todos os utilizadores.
      responses:
        '200':
          description: Lista de utilizadores obtida com sucesso.
        '500':
          description: Erro interno do servidor ao obter utilizadores.
  /nutri/adicionar:
    post:
      summary: Adicionar dados à tabela nutricional.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yearstart:
                  type: string
                yearend:
                  type: string
                locationabbr:
                  type: string
      responses:
        '201':
          description: Dado adicionado com sucesso à tabela nutricional.
        '403':
          description: Acesso proibido.
        '500':
          description: Erro interno do servidor ao adicionar dados à tabela nutricional.
  /nutri/editar/{id}:
    put:
      summary: Editar informações da tabela nutricional.
      parameters:
        - name: id
          in: path
          description: ID do dado na tabela nutricional a ser editado.
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yearstart:
                  type: string
                yearend:
                  type: string
                locationabbr:
                  type: string
      responses:
        '200':
          description: Informações da tabela nutricional atualizadas com sucesso.
        '403':
          description: Acesso proibido.
        '404':
          description: Dado na tabela nutricional não encontrado.
        '500':
          description: Erro interno do servidor ao editar informações da tabela nutricional.
  /nutri/eliminar/{id}:
    delete:
      summary: Eliminar um dado da tabela nutricional.
      parameters:
        - name: id
          in: path
          description: ID do dado na tabela nutricional a ser eliminado.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dado da tabela nutricional eliminado com sucesso.
        '403':
          description: Acesso proibido.
        '404':
          description: Dado na tabela nutricional não encontrado.
        '500':
          description: Erro interno do servidor ao eliminar dado da tabela nutricional.
  /nutri:
    get:
      summary: Obter informações da tabela nutricional.
      responses:
        '200':
          description: Informações da tabela nutricional obtidas com sucesso.
        '500':
          description: Erro interno do servidor ao obter informações da tabela nutricional.
